#ifndef CODEGEN_H
#define CODEGEN_H

#include "parser.h"

// Function to initialize the code generator
void init_codegen();

// Function to generate OCM bytecode from the given AST
void generate_code(ASTNode *root);

// Function to output the generated bytecode to a file
void output_bytecode(const char *filename);

#endif // CODEGEN_H