#include <stdio.h>
#include "lexer.h"
#include "parser.h"
#include "codegen.h"

int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <expression>\n", argv[0]);
        return 1;
    }

    const char *expression = argv[1];

    // Initialize the lexer
    Lexer lexer;
    init_lexer(&lexer, expression);

    // Initialize the parser
    Parser parser;
    init_parser(&parser, &lexer);

    // Parse the expression
    ASTNode *ast = parse_expression(&parser);
    if (ast == NULL) {
        fprintf(stderr, "Error: Failed to parse expression.\n");
        return 1;
    }

    // Generate OCM bytecode
    Bytecode bytecode = generate_bytecode(ast);
    if (bytecode.size == 0) {
        fprintf(stderr, "Error: Failed to generate bytecode.\n");
        return 1;
    }

    // Output the generated bytecode
    for (size_t i = 0; i < bytecode.size; i++) {
        printf("%02X ", bytecode.instructions[i]);
    }
    printf("\n");

    // Clean up
    free_ast(ast);
    free_bytecode(&bytecode);

    return 0;
}
